variables:
  description: Automatically delete tweets, retweets, and favorites from your timeline, and, if provided, from your twitter archive as well

includes:
- from_url:
    url: https://raw.githubusercontent.com/caarlos0/.goreleaserfiles/main/build.yml
- from_url:
    url: https://raw.githubusercontent.com/caarlos0/.goreleaserfiles/main/package.yml
- from_url:
    url: https://raw.githubusercontent.com/caarlos0/.goreleaserfiles/main/release.yml
- from_url:
    url: https://raw.githubusercontent.com/caarlos0/.goreleaserfiles/main/docker.yml
