variables:
  homepage: https://github.com/caarlos0/twitter-cleaner
  repository: https://github.com/caarlos0/twitter-cleaner
  description: Automatically delete tweets, retweets, and favorites from your timeline, and, if provided, from your twitter archive as well.

includes:
- from_url:
    url: caarlos0/goreleaserfiles/main/build.yml
- from_url:
    url: caarlos0/goreleaserfiles/main/package.yml
- from_url:
    url: caarlos0/goreleaserfiles/main/release.yml
- from_url:
    url: caarlos0/goreleaserfiles/main/docker.yml
- from_url:
    url: caarlos0/goreleaserfiles/main/sbom.yml
- from_url:
    url: caarlos0/goreleaserfiles/main/cosign_checksum.yml
- from_url:
    url: caarlos0/goreleaserfiles/main/cosign_docker.yml

furies:
- account: caarlos0
